### ISSUE TITLE
[Issue] TicketingView 에서 WebView 연결시 Loading 시간 

### ISSUE THREAD

**Issue by insub4067** [Async-Swift/AsyncSwift#26]
WebView 연결시 즉각적으로 열리지 않고 다소 시간이 소요되는 것으로 보여지며
Loading 시간동안 보여질 ProgressView 제작이 필요해 보입니다

**Comment by lingostar** [comment]
일단 네비게이션을 한 뒤 로딩이 시작되어야 할 듯 합니다. 지금은 사용자의 이벤트에 아무 반응을 하지 않는 것으로 보여 다른 액션을 취하게 만들어요.

**Comment by lingostar** [comment]
d35c1a9 에서 일단 해결
