### ISSUE TITLE
[EventView] Animation 제거

### ISSUE THREAD

**Issue by insub4067** [Async-Swift/AsyncSwift#45]
>## WHAT
https://github.com/Async-Swift/AsyncSwift/blob/8a0476d6f6e4dd99b176719754bcca9129b0ea71/AsyncSwift/Observed/EventView%2BObserved.swift#L33-L35

>## WHY
이쁘지가 않습니다

**Comment by E-know** [comment]
ObservedObject에서 StateObject로 옮기면 어떤 문제점이 발생하나요?
