### ISSUE TITLE
[StampView] List 구현 

### ISSUE THREAD

**Issue by insub4067** [Async-Swift/AsyncSwift#46]
>## WHERE
https://github.com/Async-Swift/AsyncSwift/blob/8a0476d6f6e4dd99b176719754bcca9129b0ea71/AsyncSwift/Views/StampView.swift#L37-L54
>## WHY
Seminar 002 외에 다른 Stamp를 찍으면 반영되지 않습니다

**Comment by E-know** [comment]
https://github.com/Async-Swift/AsyncSwift/pull/67
해결완료!
(브랜치 이름명 수정으로 Closed 및 새로운 브랜치로 작업완료)
