### ISSUE TITLE
[StampView] State Tree 작성하기

### ISSUE THREAD

**Issue by insub4067** [Async-Swift/AsyncSwift#49]
>## WHY
- 현재 View 내에서 Logic 과 Flow 가 분명하지 않습니다. 따라서 Readable 한 Code 작성을 위해 정리가 필요해보입니다
- Universal Link, KeyChain Logic 수정등 Refactoring 진행할때에 보다 정리된 Code 와, Review 를 위함입니다

**Comment by E-know** [comment]
![Untitled (Draft)-2](https://user-images.githubusercontent.com/55151796/193467278-57b991c1-9651-4a62-a183-a5b0986df656.jpg)

위와 같은 구조로 변경하고자 합니다.

**Comment by E-know** [comment]
https://github.com/Async-Swift/AsyncSwift/pull/67
해결완료!
(브랜치 이름명 수정으로 Closed 및 새로운 브랜치로 작업완료)
