### ISSUE TITLE
[StampView] AppData에 들어가 있는 StampView Logic 을 Observed 로 이동

### ISSUE THREAD

**Issue by insub4067** [Async-Swift/AsyncSwift#50]
>## WHAT
https://github.com/Async-Swift/AsyncSwift/blob/8a0476d6f6e4dd99b176719754bcca9129b0ea71/AsyncSwift/Observed/AppData.swift#L15-L22

>## WHY
StampView 에서 사용하는 정보를 StampView+Observed 가 아닌 AppData 에서 가지고 있습니다
아키텍쳐의 의도에 따라 AppData가 아닌 StampView+Observed 로 이동이 필요합니다

**Comment by E-know** [comment]
https://github.com/Async-Swift/AsyncSwift/pull/67
해결완료!
(브랜치 이름명 수정으로 Closed 및 새로운 브랜치로 작업완료)
